import {
  AppUser, Servico, Paciente, Anamnese,
  Agendamento, Atendimento, FinanceiroMovimentacao,
} from './types';

// ─── Usuários iniciais ───────────────────────────────────────────────────────

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'u1',
    username: 'admin',
    password: '123',
    name: 'Administrador',
    role: 'ADMIN',
    avatar: 'https://picsum.photos/seed/admin_master/200/200',
    active: true,
    email: 'admin@podologypro.com.br',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'u2',
    username: 'dra.ana',
    password: '456',
    name: 'Dra. Ana Paula',
    role: 'GERENTE',
    avatar: 'https://picsum.photos/seed/ana_paula/200/200',
    active: true,
    email: 'ana@podologypro.com.br',
    createdAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'u3',
    username: 'julia',
    password: '789',
    name: 'Júlia Recepção',
    role: 'RECEPCIONISTA',
    avatar: 'https://picsum.photos/seed/julia_rec/200/200',
    active: true,
    email: 'julia@podologypro.com.br',
    createdAt: '2026-01-03T00:00:00Z',
  },
];

// ─── Serviços iniciais (podologia) ───────────────────────────────────────────

export const INITIAL_SERVICOS: Servico[] = [
  { id: 's1', nome: 'Podologia Preventiva', descricao: 'Avaliação e cuidados preventivos dos pés', valorPadrao: 120, duracaoMinutos: 45, ativo: true, corAgenda: 'bg-blue-500' },
  { id: 's2', nome: 'Tratamento Onicomicose', descricao: 'Tratamento de micose nas unhas', valorPadrao: 150, duracaoMinutos: 60, ativo: true, corAgenda: 'bg-purple-500' },
  { id: 's3', nome: 'Tratamento de Fissuras', descricao: 'Tratamento de rachaduras nos pés', valorPadrao: 100, duracaoMinutos: 40, ativo: true, corAgenda: 'bg-orange-500' },
  { id: 's4', nome: 'Tratamento Onicocriptose', descricao: 'Tratamento de unha encravada', valorPadrao: 180, duracaoMinutos: 60, ativo: true, corAgenda: 'bg-red-500' },
  { id: 's5', nome: 'Tratamento de Verruga', descricao: 'Tratamento de verruga plantar', valorPadrao: 140, duracaoMinutos: 50, ativo: true, corAgenda: 'bg-yellow-500' },
  { id: 's6', nome: 'Calo (Geral)', descricao: 'Remoção e tratamento de calosidades', valorPadrao: 90, duracaoMinutos: 30, ativo: true, corAgenda: 'bg-green-500' },
  { id: 's7', nome: 'Onicotomia', descricao: 'Corte e modelagem terapêutica das unhas', valorPadrao: 80, duracaoMinutos: 30, ativo: true, corAgenda: 'bg-teal-500' },
  { id: 's8', nome: 'Podoprofilaxia', descricao: 'Limpeza e higienização profissional dos pés', valorPadrao: 110, duracaoMinutos: 45, ativo: true, corAgenda: 'bg-cyan-500' },
];

// ─── Pacientes iniciais ─────────────────────────────────────────────────────

export const INITIAL_PACIENTES: Paciente[] = [
  {
    id: 'p1',
    nomeCompleto: 'Maria Santos Oliveira',
    cpf: '123.456.789-00',
    dataNascimento: '1985-06-15',
    sexo: 'F',
    telefone: '(11) 98765-4321',
    email: 'maria@email.com',
    endereco: 'Rua das Flores, 123',
    cidade: 'São Paulo',
    estado: 'SP',
    observacoesGerais: 'Diabética tipo 2. Atenção especial ao manejo.',
    ativo: true,
    criadoEm: '2026-01-10T10:00:00Z',
    atualizadoEm: '2026-01-10T10:00:00Z',
  },
  {
    id: 'p2',
    nomeCompleto: 'João Carlos Silva',
    cpf: '987.654.321-00',
    dataNascimento: '1972-11-30',
    sexo: 'M',
    telefone: '(11) 91234-5678',
    email: 'joao@email.com',
    endereco: 'Av. Paulista, 456',
    cidade: 'São Paulo',
    estado: 'SP',
    observacoesGerais: '',
    ativo: true,
    criadoEm: '2026-01-15T10:00:00Z',
    atualizadoEm: '2026-01-15T10:00:00Z',
  },
  {
    id: 'p3',
    nomeCompleto: 'Ana Beatriz Ferreira',
    cpf: '456.789.123-00',
    dataNascimento: '1990-03-22',
    sexo: 'F',
    telefone: '(11) 94567-8901',
    email: 'ana.b@email.com',
    endereco: 'Rua Consolação, 789',
    cidade: 'São Paulo',
    estado: 'SP',
    observacoesGerais: '',
    ativo: true,
    criadoEm: '2026-02-01T10:00:00Z',
    atualizadoEm: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p4',
    nomeCompleto: 'Carlos Roberto Matos',
    cpf: '321.654.987-00',
    dataNascimento: '1965-09-10',
    sexo: 'M',
    telefone: '(11) 97890-1234',
    email: '',
    endereco: 'Rua Augusta, 321',
    cidade: 'São Paulo',
    estado: 'SP',
    observacoesGerais: 'Hipertenso. Usa metformina.',
    ativo: true,
    criadoEm: '2026-02-10T10:00:00Z',
    atualizadoEm: '2026-02-10T10:00:00Z',
  },
  {
    id: 'p5',
    nomeCompleto: 'Fernanda Lima Costa',
    cpf: '654.321.098-00',
    dataNascimento: '1998-12-05',
    sexo: 'F',
    telefone: '(11) 93456-7890',
    email: 'fernanda@email.com',
    endereco: 'Rua Haddock Lobo, 654',
    cidade: 'São Paulo',
    estado: 'SP',
    observacoesGerais: '',
    ativo: true,
    criadoEm: '2026-02-20T10:00:00Z',
    atualizadoEm: '2026-02-20T10:00:00Z',
  },
];

// ─── Anamneses iniciais ─────────────────────────────────────────────────────

export const INITIAL_ANAMNESES: Anamnese[] = [
  {
    id: 'a1',
    pacienteId: 'p1',
    diabetico: true,
    hipertenso: false,
    gestante: false,
    problemasCirculatorios: true,
    neuropatia: false,
    alergias: 'Penicilina',
    medicamentosEmUso: 'Metformina, Insulina NPH',
    historicoMicose: true,
    historicoUnhaEncravada: false,
    historicoFissuras: true,
    dorAoAndar: false,
    sensibilidadeAlterada: true,
    observacoesClincias: 'Paciente requer cuidado redobrado. Cicatrização mais lenta.',
    criadoEm: '2026-01-10T10:30:00Z',
    atualizadoEm: '2026-01-10T10:30:00Z',
  },
  {
    id: 'a2',
    pacienteId: 'p4',
    diabetico: false,
    hipertenso: true,
    gestante: false,
    problemasCirculatorios: false,
    neuropatia: false,
    alergias: '',
    medicamentosEmUso: 'Atenolol, Metformina',
    historicoMicose: false,
    historicoUnhaEncravada: true,
    historicoFissuras: false,
    dorAoAndar: true,
    sensibilidadeAlterada: false,
    observacoesClincias: 'Queixa principal: dor ao caminhar no calcanhar.',
    criadoEm: '2026-02-10T11:00:00Z',
    atualizadoEm: '2026-02-10T11:00:00Z',
  },
];

// ─── Agendamentos iniciais (base: 2026-03-10) ────────────────────────────────

export const INITIAL_AGENDAMENTOS: Agendamento[] = [
  {
    id: 'ag1',
    pacienteId: 'p1',
    servicoId: 's1',
    criadoPorUserId: 'u3',
    dataAgendada: '2026-03-10',
    horaInicio: '09:00',
    horaFim: '09:45',
    status: 'CONFIRMADO',
    observacoes: 'Retorno preventivo - 30 dias',
    criadoEm: '2026-03-05T08:00:00Z',
    atualizadoEm: '2026-03-09T14:00:00Z',
  },
  {
    id: 'ag2',
    pacienteId: 'p2',
    servicoId: 's6',
    criadoPorUserId: 'u3',
    dataAgendada: '2026-03-10',
    horaInicio: '10:30',
    horaFim: '11:00',
    status: 'AGENDADO',
    observacoes: '',
    criadoEm: '2026-03-06T09:00:00Z',
    atualizadoEm: '2026-03-06T09:00:00Z',
  },
  {
    id: 'ag3',
    pacienteId: 'p3',
    servicoId: 's4',
    criadoPorUserId: 'u3',
    dataAgendada: '2026-03-10',
    horaInicio: '14:00',
    horaFim: '15:00',
    status: 'AGUARDANDO',
    observacoes: 'Paciente relatou piora da dor',
    criadoEm: '2026-03-07T10:00:00Z',
    atualizadoEm: '2026-03-10T08:30:00Z',
  },
  {
    id: 'ag4',
    pacienteId: 'p4',
    servicoId: 's2',
    criadoPorUserId: 'u3',
    dataAgendada: '2026-03-10',
    horaInicio: '15:30',
    horaFim: '16:30',
    status: 'AGENDADO',
    criadoEm: '2026-03-08T11:00:00Z',
    atualizadoEm: '2026-03-08T11:00:00Z',
  },
  {
    id: 'ag5',
    pacienteId: 'p5',
    servicoId: 's8',
    criadoPorUserId: 'u1',
    dataAgendada: '2026-03-11',
    horaInicio: '09:30',
    horaFim: '10:15',
    status: 'AGENDADO',
    criadoEm: '2026-03-09T09:00:00Z',
    atualizadoEm: '2026-03-09T09:00:00Z',
  },
  {
    id: 'ag6',
    pacienteId: 'p1',
    servicoId: 's3',
    criadoPorUserId: 'u3',
    dataAgendada: '2026-03-12',
    horaInicio: '11:00',
    horaFim: '11:40',
    status: 'AGENDADO',
    criadoEm: '2026-03-09T10:00:00Z',
    atualizadoEm: '2026-03-09T10:00:00Z',
  },
];

// ─── Atendimentos iniciais ───────────────────────────────────────────────────

export const INITIAL_ATENDIMENTOS: Atendimento[] = [
  {
    id: 'at1',
    pacienteId: 'p1',
    agendamentoId: undefined,
    servicoId: 's1',
    dataAtendimento: '2026-02-10',
    horaInicio: '09:00',
    horaFim: '09:45',
    status: 'FINALIZADO',
    queixaPrincipal: 'Prevenção e revisão de micose anterior',
    descricaoProcedimento: 'Avaliação geral dos pés. Aplicação de antifúngico preventivo.',
    orientacoesPaciente: 'Manter meias de algodão. Retornar em 30 dias.',
    criadoEm: '2026-02-10T09:00:00Z',
    atualizadoEm: '2026-02-10T09:45:00Z',
  },
  {
    id: 'at2',
    pacienteId: 'p2',
    servicoId: 's6',
    dataAtendimento: '2026-02-15',
    horaInicio: '14:00',
    horaFim: '14:30',
    status: 'FINALIZADO',
    queixaPrincipal: 'Calosidade no pé direito causando desconforto',
    descricaoProcedimento: 'Desbridamento de calosidade plantar bilateral.',
    orientacoesPaciente: 'Usar palmilha de silicone por 30 dias.',
    criadoEm: '2026-02-15T14:00:00Z',
    atualizadoEm: '2026-02-15T14:30:00Z',
  },
];

// ─── Financeiro inicial ──────────────────────────────────────────────────────

export const INITIAL_FINANCEIRO: FinanceiroMovimentacao[] = [
  {
    id: 'f1',
    tipo: 'ENTRADA',
    categoriaPrincipal: 'SERVICO',
    descricao: 'Podologia Preventiva - Maria Santos',
    valor: 120,
    formaPagamento: 'PIX',
    dataMovimentacao: '2026-03-10',
    pacienteId: 'p1',
    criadoPorUserId: 'u1',
    criadoEm: '2026-03-10T09:50:00Z',
  },
  {
    id: 'f2',
    tipo: 'ENTRADA',
    categoriaPrincipal: 'SERVICO',
    descricao: 'Calo (Geral) - João Silva',
    valor: 90,
    formaPagamento: 'Cartão Crédito',
    dataMovimentacao: '2026-03-10',
    pacienteId: 'p2',
    criadoPorUserId: 'u1',
    criadoEm: '2026-03-10T11:05:00Z',
  },
  {
    id: 'f3',
    tipo: 'SAIDA',
    categoriaPrincipal: 'DESPESA',
    subcategoria: 'Material',
    descricao: 'Compra de insumos - luvas e curativos',
    valor: 280,
    formaPagamento: 'Cartão Débito',
    dataMovimentacao: '2026-03-10',
    criadoPorUserId: 'u1',
    criadoEm: '2026-03-10T12:00:00Z',
  },
  {
    id: 'f4',
    tipo: 'ENTRADA',
    categoriaPrincipal: 'PRODUTO',
    descricao: 'Creme Ureia 10% - Venda',
    valor: 45,
    formaPagamento: 'Dinheiro',
    dataMovimentacao: '2026-03-09',
    criadoPorUserId: 'u3',
    criadoEm: '2026-03-09T16:00:00Z',
  },
  {
    id: 'f5',
    tipo: 'SAIDA',
    categoriaPrincipal: 'DESPESA',
    subcategoria: 'Energia',
    descricao: 'Conta de Energia Elétrica',
    valor: 420,
    formaPagamento: 'Boleto',
    dataMovimentacao: '2026-03-08',
    criadoPorUserId: 'u1',
    criadoEm: '2026-03-08T10:00:00Z',
  },
  {
    id: 'f6',
    tipo: 'ENTRADA',
    categoriaPrincipal: 'SERVICO',
    descricao: 'Tratamento Fissuras - Maria Santos',
    valor: 100,
    formaPagamento: 'PIX',
    dataMovimentacao: '2026-02-10',
    pacienteId: 'p1',
    criadoPorUserId: 'u1',
    criadoEm: '2026-02-10T09:50:00Z',
  },
  {
    id: 'f7',
    tipo: 'ENTRADA',
    categoriaPrincipal: 'SERVICO',
    descricao: 'Calo (Geral) - João Silva',
    valor: 90,
    formaPagamento: 'PIX',
    dataMovimentacao: '2026-02-15',
    pacienteId: 'p2',
    criadoPorUserId: 'u1',
    criadoEm: '2026-02-15T14:35:00Z',
  },
];
